### ISSUE TITLE
week5_JY

### ISSUE THREAD

**Issue by yellow2041** [kmes055/AutoDrawer#25]
이번주에 할 것....(한 것...?)(9.30~10.6)
1. 리액트 네이티브 설치 완료, 프로젝트 시작해봄
2. 노마드 코더 바닐라 JS 1,2과정 수료(아직 1만끝남)
3. 구글링을 통해 리액트 네이티브 알아보기...^^

**Comment by kmes055** [comment]
Technical stack share 이슈에 남겨주세요
