### ISSUE TITLE
File Send/Receive

### ISSUE THREAD

**Issue by hacking-racoon** [kmes055/AutoDrawer#30]

**Comment by hacking-racoon** [comment]
I implemented this feature. In android-java.

to make this feature work well, I'm studying React Java,

Afterwords, I will implement this feature in React Java.

**Comment by hacking-racoon** [comment]
I implemented this feature. In React Native Expo.
I used expo-image-picker & expo-permissions.

To implement in RN Expo environment is much more easier than Android Studio.
However, I had some troubles on that.

1. php.ini ----  post_max_size, upload_max_size value was too low
2. typing error.

these error were solved by checking server log file.
I learned a lot about that.

**Comment by hacking-racoon** [comment]
However I still have technical difficulties for file_receive_transfer.

That is. 'How to know whether the conversion is done or not?'

and, I will solve this problem with async function.

for this work well. I would learn Node.js.

ll RN ll ->  async upload -> async requestPicture  llServerll -> requestConversion -> llGoogle Colabll

-> llserver ll ---- image --> ll RN ll

**Comment by kmes055** [comment]
@hacking-racoon Can you write the comment describes transaction file format here?
or you can just check and point out any wrong in my description below.

Values are just sample strings. please not focus on value, but key.
+ I understand our image is encoded in base64 format, success to import it.

method: POST(maybe additional GET request after transform)

method.body{
    'file': file {
    'type': 'image/jpg',
    'uri': <selectedPicture에 저장된 uri>,
    'name': 'uploadimagetmp.jpg',
    'token': <some_random_sequence> # Not should be called by API. any unique string is okay, we can discuss this in meeting.
    }
    'submit': 'ok' # maybe variable for check in client environment?
}

**Comment by kmes055** [comment]
Additionally, I need some more information on the client's request.

- category: String. maybe in 'bag', 'shoes', 'hat'. Default None(MUST selected by the user.)
- get_recommendation: Boolean. if True we'll show other categories, else don't. default True.

**Comment by kmes055** [comment]
+ Add) Server should know the pattern is just color or image.
I need some more variables.
- pattern: Image or String. Decided by pattern_type. base64 format will compatible with the sketch image handler.
- pattern_type: String(or Boolean). should be in 'image', 'color'. if 'color', the server should make a mono-color image by the color string.

**Comment by hacking-racoon** [comment]
There are entire process of appending body. (on upload prototype)

    let uploadData = new FormData();
    uploadData.append('submit', 'ok');
    uploadData.append('file', { type: 'image/jpg', uri: this.state.selectedPicture, name: 'uploadimagetmp.jpg' });

I  only 2 key : 'submit', 'file'

If you require any other key&value, please add comments.

**Comment by kmes055** [comment]
Draft of the JSON structure

'sketch _(changed from file)_ ': {
	'content_type': 'image/jpg',
	'uri': \<uri address of sketch image\>,
	'name': <some_name> + '.jpg',
	'token': <some_unique_string>,
}
'submit': 'ok'

# Add
'category': String. should be one of 'bag', 'shoes', 'hat'. default: null(MUST selected by the user.)
'get_recommendation': Boolean.  If true, we'll show other categories. default: True.
'pattern': {
	'Is_color': Boolean. the backend part of reading 'image_info' is dependent on this.
	'content_type': String. pattern is an image, image/jpg, image/png, etc. <b>BUT</b> must be 'text/plain' if pattern is a color.
	'image_info(you can change the name as you want)': String. if is_color == true, 6-digit color information(RGB), else uri path of image.
}

----------------------------
JSON data format is not mattered when well discussed and shared. don't afraid to say you should modify JSON format.
