### ISSUE TITLE
Please post the information to prepare for the next PPT !

### ISSUE THREAD

**Issue by hacking-racoon** [kmes055/AutoDrawer#37]
I'm preparing for the next PPT.

I need some information for you.  (Up to  ~ Saturday midnight)

please simply send to me!
 
--- AI --- 

1. frameworks & tools description ( what you've used.  that is... 'until now'. )

2. screen shots
   - datasets
   - AWS remote
   - colab connection
   - Server open
3. references
4. other problems.

Thank you !!

--- App FE ---
1. frameworks & tools description
2. Screenshot
  -  completed screen shot in App. 
  -  required functions on each button.
3. references
4. other problems

Thank you!
--------------------------------------

Please simply send to me!

**Comment by kmes055** [comment]
Wrote [Here](https://github.com/kmes055/AutoDrawer/issues/24#issuecomment-541326082) and [Here](https://github.com/kmes055/AutoDrawer/issues/24#issuecomment-541326082)

Add:
Please mention that for time limit, our team will explain AI backend & theory deeper in the next presentation.

**Comment by kmes055** [comment]
![image20191013_5](https://user-images.githubusercontent.com/31791620/66712478-291d0f80-edd8-11e9-9282-d68ff653e871.jpg)

**Comment by kmes055** [comment]
For another issue, please read [This issue](https://github.com/kmes055/AutoDrawer/issues/39)

**Comment by kmes055** [comment]
Sorry for so many comments. please read [This](https://github.com/kmes055/AutoDrawer/issues/24#issuecomment-541396254). This will help you to write references.
