### ISSUE TITLE
백엔드 기능 추가시 문제점들

### ISSUE THREAD

**Issue by hacking-racoon** [kmes055/AutoDrawer#50]
1. switchNavigator 스와이프시 props 전달 이슈.
    https://reactnavigation.org/docs/en/auth-flow.html
    방법은 명시되어 있지만 불필요하게 길고 우아한 방법이 아닌 것 같음 
    
    현재는 일단 '뒤로' 버튼을 이용하여 돌아가면서 prop전달을 유도함

2. 사진 객체 연결시 파일명 이슈
    마일스톤대로 파일명 표시를 구현함, 하지만 파일명 구현 의미가 없다고 생각
    갤러리 파일 주소는 파일 코드와 사람이 이해하기 힘든 영어 코드.
    파일명을 통해 사용자가 얻는 정보가 없음.
    객체 연결이 제대로 됐는지를 확인하는 용도라면  체크표시나 사진 표시가 적절하다고 생각

이외 추가된 코드에 대한 설명은 메일로 첨부할 예정.

--> 마일스톤, 백엔드 구현 완성
   
남은 작업: 세부 안정화 작업, AI 구현 이후 파일주고받기, 로그인 인증

구글로그인은 시간이 남으면 이번주에 시도할 예정임

**Comment by kmes055** [comment]
Redux 도입으로 해결
