### ISSUE TITLE
발표자료만들기

### ISSUE THREAD

**Issue by kmes055** [kmes055/AutoDrawer#53]
슈르르뽕뽕후르르

**Comment by kmes055** [comment]
AI 변경: TextureGAN으로 변경
데이터셋은 아직도 찾고있음 ㅜㅜ

서버
EC2 버림
Apache는 Python backend를 이용하기 위해 합리적인 django로 변경
그냥 django 씀
서버에서 그뭐냐 그그 파라미터 보냄(파일은 경로만)

앱
Expo 소개

웹2000줄 AI5000 Server 1000 총8000

size App/Web 20MB 이내, AI binary 10MB 이내, Dataset: 30GB

Memory App/Web 200MB / AI 최소 4.3GB
상세구조 재정리

개발비용에서 AWS -> Django


[5] TextureGAN
[6] HED
[7] A. Yu and K. Grauman. "Fine-Grained Visual Comparisons with Local Learning". In CVPR, 2014.
[8] A. Yu and K. Grauman. "Semantic Jitter: Dense Supervision for Visual Comparisons via Synthetic Images". In ICCV, 2017.
[9] Zhu et al. Generative Visual Manipulation on the Natural Image Manifold

**Comment by yellow2041** [comment]
FE 레이아웃 구현 진행상황
---------------------------------
home, menu, palette, start loading, transfer loading, menu sliding, result layout 구현 완료.

FE 간트차트 변경 내용
-----------------------------------------------------------------------------------------
result layout 추가, 기타 오류 해결 필요, 로그인 시 나타날 화면 구현 추가

해결해야 할 사항
-------------------------------------
1. 다른 화면에서 다시 홈으로 돌아오거나 output 화면의 메뉴바가 열리지 않음
- App.js의 네비게이터 구조를 바꿔야 할 것 같음(drawer navigator와 stack navigator의 관계)
2. transfer loading 화면에서 실시간으로 서버에서 진행 상황 받아와서 loading bar 진행시키기
3. 로그인 전과 후의 화면 구성하기

**Comment by kmes055** [comment]
Server, AI 진행상황
Django 구축중.. 화면은 만들 필요 없어서 없고, post/get 함수에 대한 response 구현중. 현재는 이미지 변환부분은 그냥 sketch를 return함. 쓰레드 문제랑 progressbar를 위한 신호를 고민중

로그인 구현 여부에 따라 달라질 수 있긴 한데, 토큰 기반 인증을 생각중이고, 유저 정보를 보안성은 유지하면서 악의적인 공격은 막는 한에서 사용해야 하는데 이 부분은 아직 논의가 필요함

CycleGAN이 학습이 이상하게 돼서 DiscoGAN으로 변경. 
일단 여기까지...계속 적을게요

**Comment by kmes055** [comment]
AI는 학습중이며, Serialize 구현중입니다. 멀티쓰레드로 구현하고자 하는데 아직은 모르겠어요

Django에서는 기본적으로 파라미터만 전달하며, 이 파라미터들로 AI세션(코랩)에서 커맨드를 실행해서 변환하고 다시 서버로 올리는 방식으로 구현 예정입니다

서버는 기본적으로 파일 전송 역할만 수행하며, 보안 관련된 내용은 검토중입니다
