### ISSUE TITLE
We need to refactor file structure

### ISSUE THREAD

**Issue by kmes055** [kmes055/AutoDrawer#54]
Reducers
ㄴindex.js
ㄴmetadataReducer.js
ㄴpatternReducer.js
ㄴsketchReducer.js
Actions
ㄴbaseAction.js // 나중에 분리할 예정이긴 한데, 일단 여기 정리해놨어요
ㄴindex.js
ㄴtypes.js
Components
ㄴsketch, pattern, home 등 App.js 제외한 화면들 들어가면 좋을거같아요

-----------------------------------------------------------------------------
그리고 action, reducer, store 등 객체 작성을 위해 각 component별로 state에 필요한 변수들을 여기 정리해두고 싶습니다
각 component별 이름 / type / 기능을 간단하게 적어주세염
예) 
Palette
oldColor : String. RGB color information
Color: Dictionary? HSV color information
etc...

**Comment by hacking-racoon** [comment]
home -
    sketchSelected
    patternSelected

*  selected 변수는 sketch, palette 컴포넌트에서 불러온 값들이 저장됨.
   갤러리에서 가져오든, 직접 찍든, 그냥 패턴, 스케치로 저장되는것임

    Token -- 토큰
    isLogined -- 로그인 여부
    name -- 토큰으로 가져옴,  차형진님 안녕하세요 이런식으로 활용

Pattern - 
    patternGallery
    patternPalette

* 갤러리/ 파레트에서 가져온 패턴 저장

Sketch -
    sketchGallery
    sketchTaken

* 갤러리에서 가져오거나 직접 찍은 스케치 저장
Transpose
    sketchSelected
    patternSelected
    isLogined
    generatedImage

* 선택된 스케치/ 패턴 이미지 저장,
* 로그인 됐는지 여부 저장 (권한 관리)
* 생성된 이미지 저장

**Comment by yellow2041** [comment]
transfer진행 상황을 받아 올 progressStatus 필요

**Comment by kmes055** [comment]
+이미 논의된 것들이나 딱봐도 필요한 수준에서 Action들(state 변환하는 함수들) 만들건데, 혹시 '이건 놓치실 것 같아요!' 싶은 함수 있으면 코멘트 달아주세요

**Comment by yellow2041** [comment]
FE 필요한 변수 정리
--------------------------
#### 1. home.js
> - selectedSketch(스케치버튼 클릭 후 가져온 사진의 uri)
> - selectedPattern(패턴버튼 클릭 후 가져온 패턴 사진의 uri 또는 RGB 색상 코드)
#### 2. Sketch.js
> - selectedPicture(선택된 스케치 사진의 uri, 카메라랑 앨범 중 어느것을 선택해도 이 변경되는건 이 변수)
#### 3. Pattern.js
> - selectedResult(앨범에서 패턴 사진을 고를 시 해당 사진의 uri를 담거나 팔레트에서 받아온 색상 코드를 담음)
#### 4. Palette.js
> - newColor(사용자가 선택한 새로운 컬러 코드)
> - oldColor(사용자가 이전에 선택했던 컬러 코드)
#### 5. ProgressBarComponent.android.js
> - prograssStatus(transform 진행 상황에 따라 업데이트 되어 프로그레스 바에 반영 될 진행률)
#### 6. transpose.js
> - resultPicture(완성된 결과물 사진을 받아올 변수)
> - recommend1(추천 제품 사진 1)
> - recommend2(추천 제품 사진 2)
> - recommend3(추천 제품 사진3)
## 추가 구현 사항
> - myHistory.js (사용자가 지금까지 만든 사진들 모아놓는곳)
>> userName(화면에 띄울 사용자 이름), userInfo(사용자 정보)

> - login.js (로그인하는 화면)
>> userName

**Comment by kmes055** [comment]
End.
