### ISSUE TITLE
발표자료 만들기

### ISSUE THREAD

**Issue by hacking-racoon** [kmes055/AutoDrawer#56]
발표를 위해 각자 진행한 파트들을 올려주세요.

**Comment by kmes055** [comment]
![image20191123_4](https://user-images.githubusercontent.com/31791620/69475263-5795fd80-0e0e-11ea-8273-c721e735890c.jpg)
Redux 구현 코드
![image20191123_5](https://user-images.githubusercontent.com/31791620/69475265-595fc100-0e0e-11ea-98e4-30191d0b3e3a.jpg)
각 Component에서 쓸 수 있는 template code
![image20191123_6](https://user-images.githubusercontent.com/31791620/69475266-5b298480-0e0e-11ea-8967-9451585fa09e.jpg)
실제 사용 예(Palette)

주석 읽어보시고, 이해 어려운 부분 있으면 알려주세염

**Comment by yellow2041** [comment]
![image](https://user-images.githubusercontent.com/37579982/69482441-c26f2500-0e5e-11ea-97b8-a7f0e06ef5ee.png)
현재 App.js의 네비게이션 구조

![image](https://user-images.githubusercontent.com/37579982/69482490-6953c100-0e5f-11ea-98fb-8e581bd08863.png)
마이페이지에서 이미지를 화면에 표시하는 함수(아직 실제 이미지와 연결하진 않음)

![KakaoTalk_20191124_015354060](https://user-images.githubusercontent.com/37579982/69482504-9c965000-0e5f-11ea-8667-38535b818a44.jpg)
마이페이지

![KakaoTalk_20191124_021200587](https://user-images.githubusercontent.com/37579982/69482516-da937400-0e5f-11ea-8911-0eed817e0125.jpg)
현재 메뉴바 구성(필요에 따라 변경)

-------------------------------------------------------------
* RN에서 네비게이션을 이용하는 것이 아니라 그냥 단순히 이미지 넘기는건 어떻게 하는건지 찾아보기(튜토리얼 화면 넘기는것)
* 로그인은 eject하기 전에 어떤 화면을 먼저 만들어놓으면 좋을지 생각해보기
* 백엔드랑 연결되면 마이페이지의 사진 삭제와 저장은 어떻게 할것인지 생각해보기
